In [1]:
import pandas as pd
import numpy as np
import warnings

# Tắt tất cả các cảnh báo
warnings.filterwarnings("ignore")

In [2]:
# Đọc dữ liệu từ file csv
df = pd.read_csv('smarthub/spiders/smarthub_products.csv')
df.head()

,product_name,brand,price,ram,storage,screen_size,resolution,chipset,os,rear_camera,front_camera,battery,dimensions,weight,rating_value,rating_count,image_url
0,Xiaomi Redmi 15C,Xiaomi,4099000,8,256.0,6.90,720x1600,Helio G81 Ultra (12 nm),Xiaomi HyperOS 2,Chính 50 MP & Phụ QVGA,8 MP,6000,171.56x79.47x7.99,205,5,1,https://www.duchuymobile.com/images/detailed/9...
1,realme C85 5G,Realme,6289000,8,128.0,6.80,720x1570,Dimensity 6300 5G 8 nhân,Android 15,Chính 50 MP & Cảm biến Flicker,8 MP,7000,164.4x77.99x8.09,205,5,1,https://www.duchuymobile.com/images/detailed/9...
2,HONOR 600 Lite 5G,HONOR,9299000,12,256.0,1.00,1200x2600,Dimensity 7100 Elite (6 nm),"Android 16, MagicOS 10",108 + 5 MP,"16 MP, f/2.5",6520,157.4x75.4x7.3,180,5,1,https://www.duchuymobile.com/images/detailed/9...
3,Realme P4 Lite,Realme,2849000,4,64.0,6.74,720x1600,Unisoc T7250 (12 nm),"Android 15, Realme UI 5.0",13 MP,5 MP,6300,167.2x76.6x7.9,201,5,1,https://www.duchuymobile.com/images/detailed/9...
4,Tecno Camon 50,Tecno,7549000,8,256.0,6.78,1208x2644,Helio G200 Ultimate,"Android 16, HIOS 16",50 + 8 MP,"32 MP, f/2.5",6150,NaN,NaN,5,1,https://www.duchuymobile.com/images/detailed/9...

In [3]:
# Kiểm tra các dòng dữ liệu có giá trị bị thiếu (NaN)
df.isnull().sum()

product_name     50
brand            98
price             0
ram              88
storage          84
screen_size      80
resolution      136
chipset          88
os               85
rear_camera      90
front_camera     90
battery          78
dimensions      270
weight          289
rating_value      0
rating_count      0
image_url         0
dtype: int64

In [4]:
# Loại bỏ các dòng có giá trị bị thiếu
df = df.dropna()

# Loại bỏ các dòng trùng lặp product_name
df = df.drop_duplicates(subset=["product_name"])

# Loại bỏ các sản phẩm không phải điện thoại (ví dụ: Ốp Lưng)
df = df[~df["product_name"].str.contains("Ốp Lưng", case=False, na=False)]

# Loại bỏ các sản phẩm có chữ "cũ"
df = df[~df["product_name"].str.contains("cũ", case=False, na=False)]

# Xử lý cột battery
df["battery"] = pd.to_numeric(df["battery"].astype(str).str.replace(".", "", regex=False), errors="coerce")
df["battery"].fillna(df["battery"].median(), inplace=True)

# Xử lý cột weight
df = df[pd.to_numeric(df["weight"], errors="coerce").notna()]

# Xử lý cột ram
df = df[pd.to_numeric(df["ram"], errors="coerce").notna()]

In [5]:
# Kiểm tra các dòng dữ liệu có giá trị bị thiếu (NaN)
df.isnull().sum()

product_name    0
brand           0
price           0
ram             0
storage         0
screen_size     0
resolution      0
chipset         0
os              0
rear_camera     0
front_camera    0
battery         0
dimensions      0
weight          0
rating_value    0
rating_count    0
image_url       0
dtype: int64

In [6]:
# Đặt seed để kết quả ổn định khi chạy lại
np.random.seed(42)

# 1️. Tạo tỷ lệ giảm giá ngẫu nhiên (8% - 30%)
discount_rate = np.random.uniform(0.08, 0.30, len(df))

# 2️. Tính original_price từ price
df["original_price"] = (df["price"] / (1 - discount_rate)).round(-4)

# Đảm bảo original_price luôn lớn hơn price
df["original_price"] = np.where(
    df["original_price"] <= df["price"],
    df["price"] * 1.1,
    df["original_price"]
).round(-4)

# 3. Tạo stock ngẫu nhiên (0 - 120)
df["stock"] = np.random.randint(0, 121, len(df))

# 4. Thêm cột status mặc định = active
df["status"] = "active"

df.head()

,product_name,brand,price,ram,storage,screen_size,resolution,chipset,os,rear_camera,front_camera,battery,dimensions,weight,rating_value,rating_count,image_url,original_price,stock,status
0,Xiaomi Redmi 15C,Xiaomi,4099000,8,256.0,6.90,720x1600,Helio G81 Ultra (12 nm),Xiaomi HyperOS 2,Chính 50 MP & Phụ QVGA,8 MP,6000.0,171.56x79.47x7.99,205,5,1,https://www.duchuymobile.com/images/detailed/9...,4890000.0,34,active
1,realme C85 5G,Realme,6289000,8,128.0,6.80,720x1570,Dimensity 6300 5G 8 nhân,Android 15,Chính 50 MP & Cảm biến Flicker,8 MP,7000.0,164.4x77.99x8.09,205,5,1,https://www.duchuymobile.com/images/detailed/9...,8850000.0,0,active
2,HONOR 600 Lite 5G,HONOR,9299000,12,256.0,1.00,1200x2600,Dimensity 7100 Elite (6 nm),"Android 16, MagicOS 10",108 + 5 MP,"16 MP, f/2.5",6520.0,157.4x75.4x7.3,180,5,1,https://www.duchuymobile.com/images/detailed/9...,12250000.0,39,active
3,Realme P4 Lite,Realme,2849000,4,64.0,6.74,720x1600,Unisoc T7250 (12 nm),"Android 15, Realme UI 5.0",13 MP,5 MP,6300.0,167.2x76.6x7.9,201,5,1,https://www.duchuymobile.com/images/detailed/9...,3610000.0,63,active
6,HONOR X7d 5G,HONOR,5389000,8,256.0,6.77,720x1610,Snapdragon 6s Gen 3,Android 15,50 + 2 MP,8MP,6500.0,166.89x76.8x8.24,208,5,1,https://www.duchuymobile.com/images/detailed/8...,6080000.0,21,active

In [7]:
# Đảm bảo thứ tự cột: Đưa status, original_price, stock gần cuối, image_url luôn là cột cuối
cols = [c for c in df.columns if c not in ["status","original_price","stock","image_url"]]
df = df[cols + ["status","original_price","stock","image_url"]]

In [8]:
# Lưu dữ liệu vào file csv mới
df.to_csv("smarthub_products_final.csv", index=False, encoding="utf-8-sig")

In [9]:
# Thống kê số lượng sản phẩm theo từng thương hiệu
df["brand"].value_counts()

brand
Xiaomi      110
Samsung      97
Vivo         92
OPPO         84
Realme       78
HONOR        54
Apple        51
Motorola     29
Google       23
Nubia        21
OnePlus      21
Huawei       18
Tecno        16
Infinix      16
Nothing       8
RedMagic      2
Nokia         2
Name: count, dtype: int64